name: recommender
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pandas
  - numpy
  - scikit-learn
  - scikit-surprise
  - plotly
  - nbformat
  - ipykernel
#conda env create -f conda_env.yaml